name: TooManyIcons
version: @version@
main: me.datatags.toomanyicons.TooManyIcons
api-version: 1.13
commands:
    tmi:
        description: Trigger rewards or change reward settings
        permission: toomanyicons.use
        usage: /<command> [args]
